;; ======================================
;; 仓颉桥接 (Cangjie Bridge) 示例
;; ======================================

(println "=== Xisp 仓颉桥接演示 ===")
(println "")

(println "1. 桥接概念")
(println "通过 cangjie:: 命名空间调用仓颉标准库")
(println "")

(println "2. 文件系统模块 (std.fs)")
(println "代码: (cangjie::exists? \".\")")
(define dot-exists (cangjie::exists? "."))
(println #"当前目录存在: #{dot-exists}")
(println "期望: true")
(println "")

(println "3. 检查文件类型")
(println "代码: (cangjie::file? \"README.md\")")
(define is-readme (cangjie::file? "README.md"))
(println #"README.md 是文件: #{is-readme}")
(println "期望: true")
(println "")
(println "代码: (cangjie::directory? \".\")")
(define is-current-dir (cangjie::directory? "."))
(println #". 是目录: #{is-current-dir}")
(println "期望: true")
(println "")

(println "4. 列出目录内容")
(println "代码: (cangjie::list-dir \".\")")
(define dir-list (cangjie::list-dir "."))
(println #"当前目录文件数量: #{(length dir-list)}")
(println "")

(println "5. 桥接的错误处理")
(println "读取不存在的文件会返回 nil 而不是报错")
(define missing (cangjie::read-file "nonexistent.txt"))
(println #"结果: #{missing}")
(println "期望: nil")
(println "")

(println "6. 桥接的优势")
(println "- 无需在 Lisp 中重新实现标准库")
(println "- 直接使用仓颉生态系统的所有功能")
(println "- 类型安全的互操作")
(println "")

(println "7. 可用桥接函数列表")
(println "文件操作:")
(println "  cangjie::read-file    读取文件内容")
(println "  cangjie::write-file   写入文件")
(println "  cangjie::append-file  追加内容到文件")
(println "")
(println "文件系统:")
(println "  cangjie::exists?      检查文件/目录是否存在")
(println "  cangjie::file?        判断是否为文件")
(println "  cangjie::directory?   判断是否为目录")
(println "  cangjie::list-dir     列出目录内容")
(println "  cangjie::current-dir  获取当前工作目录")
(println "")

(println "8. 实际应用示例")
(println "检查项目目录结构")
(define has-src (cangjie::exists? "src"))
(define has-examples (cangjie::exists? "examples"))
(define has-docs (cangjie::exists? "docs"))
(println #"  src 目录存在: #{has-src}")
(println #"  examples 目录存在: #{has-examples}")
(println #"  docs 目录存在: #{has-docs}")
(println "")

(println "=== 仓颉桥接演示完成 ===")
(println "")
(println "更多信息请参考:")
(println "  - docs/integration/bridge.md")
