;; ======================================
;; 闭包与函数组合 (Closures) 示例
;; ======================================

(println "=== Xisp 闭包演示 ===")
(println "")

(println "1. 基本闭包 - 计数器")
(println "代码: (define (make-counter) (let ((count 0)) (lambda () (set! count (+ count 1)) count)))")
(define (make-counter)
  (let ((count 0))
    (lambda ()
      (set! count (+ count 1))
      count)))
(define counter1 (make-counter))
(println #"第一次调用 (counter1): #{(counter1)}")
(println "期望: 1")
(println #"第二次调用 (counter1): #{(counter1)}")
(println "期望: 2")
(println #"第三次调用 (counter1): #{(counter1)}")
(println "期望: 3")
(println "")

(println "2. 多个独立计数器")
(println "代码: 创建两个独立的计数器 counter2 和 counter3")
(define counter2 (make-counter))
(define counter3 (make-counter))
(println #"counter2: #{(counter2)}")
(println "期望: 1")
(println #"counter3: #{(counter3)}")
(println "期望: 1")
(println #"counter2: #{(counter2)}")
(println "期望: 2")
(println #"counter3: #{(counter3)}")
(println "期望: 2")
(println "")

(println "3. 带参数的闭包 - 加法器工厂")
(println "代码: (define (make-adder n) (lambda (x) (+ x n)))")
(define (make-adder n)
  (lambda (x) (+ x n)))
(define add10 (make-adder 10))
(define add100 (make-adder 100))
(println #"(add10 5): #{(add10 5)}")
(println "期望: 15")
(println #"(add100 50): #{(add100 50)}")
(println "期望: 150")
(println "")

(println "4. 闭包保存私有状态")
(println "代码: 工厂函数返回多个闭包来访问私有状态")
(println "")
(define (make-counter start)
  (let ((count start))
    (list
      (lambda () (set! count (+ count 1)) count)
      (lambda () count)
      (lambda (n) (set! count n)))))
(define counter-with-reset (make-counter 100))
(define next-c (first counter-with-reset))
(define get-c (second counter-with-reset))
(define reset-c (third counter-with-reset))
(println #"初始: #{(get-c)}")
(println "期望: 100")
(println #"第一次 next: #{(next-c)}")
(println "期望: 101")
(println #"第二次 next: #{(next-c)}")
(println "期望: 102")
(reset-c 500)
(println #"重置后: #{(get-c)}")
(println "期望: 500")
(println "")

(println "5. 函数组合")
(println "代码: (define (compose f g) (lambda (x) (f (g x))))")
(define (compose f g)
  (lambda (x) (f (g x))))
(define square (lambda (x) (* x x)))
(define increment (lambda (x) (+ x 1)))
(define square-then-inc (compose increment square))
(define inc-then-square (compose square increment))
(println #"(square-then-inc 5): #{(square-then-inc 5)}")
(println "期望: 26 (square(5) = 25, then + 1)")
(println #"(inc-then-square 5): #{(inc-then-square 5)}")
(println "期望: 36 (5 + 1 = 6, then square)")
(println "")

(println "6. 高阶函数返回函数")
(println "代码: (define (make-predicate op) (lambda (threshold) (lambda (x) (op x threshold))))")
(define (make-predicate op)
  (lambda (threshold)
    (lambda (x) (op x threshold))))
(define gt (make-predicate >))
(define lt (make-predicate <))
(define greater-than-10 (gt 10))
(define less-than-5 (lt 5))
(println #"(greater-than-10 15): #{(greater-than-10 15)}")
(println "期望: true")
(println #"(greater-than-10 5): #{(greater-than-10 5)}")
(println "期望: false")
(println #"(less-than-5 3): #{(less-than-5 3)}")
(println "期望: true")
(println #"(less-than-5 10): #{(less-than-5 10)}")
(println "期望: false")
(println "")

(println "=== 闭包演示完成 ===")
