;; ============================================
;; 命名参数和默认值 (Keyword Args) 示例
;; ============================================

(println "=== Xisp 命名参数和默认值演示 ===")
(println "")

(println "1. 可变参数 (&rest)")
(println "代码: (define (list-all . args) args)")
(define list-all (lambda (&rest args) args))
(println "调用: (list-all 1 2 3 4)")
(println #"结果: #{(list-all 1 2 3 4)}")
(println "期望: (1 2 3 4)")
(println "")

(println "2. 混合位置参数和可变参数")
(println "代码: (define (show-info name . details)")
(println "      (show-info \"Alice\" \"Age: 25\" \"City: Beijing\")")
(define show-info (lambda (name . details)
  (begin
    (println "Name: " name)
    (println "Details: " details))))
(show-info "Alice" "Age: 25" "City: Beijing")
(println "")
(println "3. 纯可变参数函数")
(println "代码: (define (sum-all . numbers) (apply + numbers))")
(define sum-all (lambda (. numbers) (apply + numbers)))
(println "调用: (sum-all 1 2 3 4 5)")
(println #"结果: #{(sum-all 1 2 3 4 5)}")
(println "期望: 15")
(println "")

(println "4. 命名参数 (&key)")
(println "代码: (define (create-person &key name age city)")
(println "      (create-person :name \"张三\" :age 25 :city \"北京\")")
(define create-person (lambda (&key name age city)
  (list "name:" name "age:" age "city:" city)))
(println "调用1: 按顺序传递")
(println (create-person :name "张三" :age 25 :city "北京"))
(println "调用2: 按任意顺序")
(println (create-person :city "上海" :name "李四" :age 30))
(println "调用3: 只传递部分参数")
(println (create-person :name "王五"))
(println "")

(println "5. 默认值")
(println "代码: (define (connect &key (host \"localhost\") (port 8080) (ssl #f))")
(println "      (connect)")
(println "      (connect :port 9000)")
(define connect (lambda (&key (host "localhost") (port 8080) (ssl #f))
  (list "host:" host "port:" port "ssl:" ssl)))
(println "使用默认值:")
(println (connect))
(println "\n覆盖部分默认值:")
(println (connect :port 9000))
(println "\n覆盖所有默认值:")
(println (connect :host "example.com" :port 443 :ssl #t))
(println "")

(println "6. 混合位置参数、命名参数和可变参数")
(println "代码: (define (process a b &key x y &rest opts)")
(println "      (process 1 2 :x 10 :y 20 :opt1 :opt2)")
(define process (lambda (a b &key x y &rest opts)
  (list "a:" a "b:" b "x:" x "y:" y "opts:" opts)))
(println (process 1 2 :x 100 :y 200 :opt1 :opt2))
(println "")

(println "7. Lambda 也支持命名参数")
(println "代码: ((lambda (&key x y) (list x y)) :x 5 :y 10)")
(println ((lambda (&key x y) (list x y)) :x 5 :y 10))
(println "")

(println "=== 命名参数和默认值演示完成 ===")
